### ISSUE TITLE
Make it possible to pause

### ISSUE THREAD

**Issue by rpglover64** [ggustafsson/Tim#5]
I know you're not supposed to pause, but it's a useful feature to avoid the dilemma between cheating and abandoning.

**Comment by ggustafsson** [comment]
Hello,

I can understand why you would want this but it will probably not be added. Thought about it for a while and I can't come up with any way of doing this in Zsh that would be good enough, if that changes I might implement it but I doubt that.

Tim is pushing the limits of what can be done in a shell script, it is a little bit crazy but fun :). This really should have been written in something like Go instead.

(I don't have any plans for a port since Tim is 99% feature complete and very solid)

**Comment by rpglover64** [comment]
Makes sense. After I posted this feature request, I realized that I could basically get what I want by `Ctrl-z` (probably).

Thanks for the great tool!

**Comment by ggustafsson** [comment]
I'm not sure if Ctrl-Z works but yeah the best way to handle this would be to try to find a way to suspend the Zsh process (and all child processes) outside of the script.

If you find anything then let me know. If you are lucky a one-liner might do the job, I'll add it to the tips section if that is the case.
